Refactor: refactored the interaction of the services with the databas…
programacion-6/ExpenseTrackerGroup6 pull request #11
Opened 2024-09-27 01:37 UTC by JosuePrado

…e, the mappers, and updated the controllers

# Pull Request Title
#### Resolved task/US: ([item title]())
* * * *

## What's in this pull request?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/programacion-6/ExPenSeTraCkerGroUpSiX/wiki/Convetions) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

## How to run it
- docker-compose up --build : execute this command in the **ROOT** of the project
- dotnet ef migrations add InitialCreate : execute this command inside the **RESTAPI** folder
- dotnet ef database update : execute this command inside the **RESTAPI** folder

2024-09-27 14:17 UTC, zrock-dev commented
Dear @JosuePrado. Please add a description to the pull request.

2024-09-27 15:05 UTC, JosuePrado commented
> Dear @JosuePrado. Please add a description to the pull request.

I just did it, thanks

2024-09-27 20:49 UTC, jhael-arce-jalafund reviewed
![image](https://github.com/user-attachments/assets/a1b2e948-f774-4382-84f5-a6147c0ad8ab)
URLs should follow Naming Conventions:

- Lowercase: URLs should always be in lowercase to avoid issues with case-sensitive systems and to maintain consistency.

          Example: /api/v1/users, not /api/v1/Users.

- Plurality: Use plural nouns to represent collections of resources, aligning with RESTful standards.

               Example: /api/v1/users, not /api/v1/user.

2024-09-27 22:40 UTC, JosuePrado commented
> ![image](https://private-user-images.githubusercontent.com/135137355/371682409-a1b2e948-f774-4382-84f5-a6147c0ad8ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NzcwOTAsIm5iZiI6MTcyNzQ3Njc5MCwicGF0aCI6Ii8xMzUxMzczNTUvMzcxNjgyNDA5LWExYjJlOTQ4LWY3NzQtNDM4Mi04NGY1LWE2MTQ3YzBhZDhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QyMjM5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjAyYTUyMWNjODQ3MWU5ZWU3YmQ1ZGI5ZWIxZTg0ZmU2ODUyMDYxZjBmY2ZhYjQwYzgzYjBjNmM4ODY2NWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g7kEOhG2WWiY9BC7JabEjvE_QeW2dFaRT8JMEDdh0ms) URLs should follow Naming Conventions:
> 
> * Lowercase: URLs should always be in lowercase to avoid issues with case-sensitive systems and to maintain consistency.
>   ```
>       Example: /api/v1/users, not /api/v1/Users.
>   ```
> * Plurality: Use plural nouns to represent collections of resources, aligning with RESTful standards.
>   ```
>            Example: /api/v1/users, not /api/v1/user.
>   ```
you are absolutely right, I just uploaded the change.

2024-09-27 22:47 UTC, jhael-arce-jalafund commented on RestApi/Services/Concretes/IncomeService.cs
> +
Please align the code for better readability. Thanks.

2024-09-28 14:10 UTC, JosuePrado commented on RestApi/Services/Concretes/IncomeService.cs
> +
The code has been aligned for better readability, :)

2024-09-28 14:16 UTC, jhael-arce-jalafund approved these changes

2024-09-28 21:31 UTC, zrock-dev requested changes
Following our DoD we need to add validations to our controllers. Please add validations to ExpensesController, IncomesController and UserController

2024-09-28 21:51 UTC, zrock-dev commented
I'm having problems to run the PR
![Kooha-2024-09-28-17-43-58.webm](https://github.com/user-attachments/assets/3e849774-4ce5-43e1-8bce-a669e686d98b)

--- 
**QUERY**

curl -X 'GET' \
  'http://localhost:5001/api/v1/expenses' \
  -H 'accept: */*
ERROR
```
Npgsql.PostgresException (0x80004005): 42P01: relation "Expense" does not exist

POSITION: 107
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at RestApi.Services.Concretes.ExpenseService.ReadAsync() in /src/RestApi/Services/Concretes/ExpensesService.cs:line 26
   at RestApi.Services.Concretes.ExpenseService.GetExpensesAsync(Nullable`1 date, String category) in /src/RestApi/Services/Concretes/ExpensesService.cs:line 67
   at RestApi.Controllers.ExpenseController.GetAll(Nullable`1 date, String category) in /src/RestApi/Controllers/ExpensesController.cs:line 29
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "Expense" does not exist
    Position: 107
    File: parse_relation.c
    Line: 1191
    Routine: parserOpenTable

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:5001
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Cookie: jenkins-timestamper-offset=14400000; structurizr.darkMode=true; screenResolution=1920x1080; JSESSIONID.cdcc472a=node015crjw3zuuskgm6l1yr5mr4h33.node0; JSESSIONID=F6CA389ABE0F30ED5A565C007A8D5367
Referer: http://localhost:5001/index.html
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
DNT: 1
Sec-GPC: 1
Priority: u=0

``` 

**Query**

curl -X 'GET' \
  'http://localhost:5001/api/v1/incomes' \
  -H 'accept: */*'

ERROR
```
Npgsql.PostgresException (0x80004005): 42P01: relation "Income" does not exist

POSITION: 66
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at RestApi.Servi [...]

2024-09-28 22:07 UTC, zrock-dev commented
Upon further inspection, I have realized this PR along with #9 have implemented these tickets as well.

- [[ID-9] Log Access](https://trello.com/c/8NS6aZk1/7-id-9-log-access)
- [[ID-13] Log edition](https://trello.com/c/TrAgdMGC/2-id-13-log-edition)
- [[ID-17]  User profile access](https://trello.com/c/GsHJpK8f/20-id-17-user-profile-access)

So maybe we can mark them as done.

As for [[ID-18]  User profile edition](https://trello.com/c/fWop8laX/22-id-18-user-profile-edition)  and [[ID-16]  User authentication](https://trello.com/c/P2oHtrHm/19-id-16-user-authentication) it seems that only the endpoints are available.

2024-09-29 03:33 UTC, JosuePrado commented
> Upon further inspection, I have realized this PR along with #9 have implemented these tickets as well.
> 
> * [[ID-9] Log Access](https://trello.com/c/8NS6aZk1/7-id-9-log-access)
> * [[ID-13] Log edition](https://trello.com/c/TrAgdMGC/2-id-13-log-edition)
> * [[ID-17]  User profile access](https://trello.com/c/GsHJpK8f/20-id-17-user-profile-access)
> 
> So maybe we can mark them as done.
> 
> As for [[ID-18] User profile edition](https://trello.com/c/fWop8laX/22-id-18-user-profile-edition) and [[ID-16] User authentication](https://trello.com/c/P2oHtrHm/19-id-16-user-authentication) it seems that only the endpoints are available.



> Following our DoD we need to add validations to our controllers. Please add validations to ExpensesController, IncomesController and UserController

I would prefer to do it in another pull given the big changes in this one.

2024-09-29 04:00 UTC, zrock-dev commented
Dear @JosuePrado, I agree with you this is a big PR. The applied refactors deal with those controllers, and to be able to mark the ticket as done it has to follow our Definition of Done. Regarding code reviewing sake I can use git commit ranges to focus the review only on the latest updates.

Also, what do you think about marking the before mentioned tickets as done?

2024-09-29 05:07 UTC, JosuePrado commented
> Dear @JosuePrado, I agree with you this is a big PR. The applied refactors deal with those controllers, and to be able to mark the ticket as done it has to follow our Definition of Done. Regarding code reviewing sake I can use git commit ranges to focus the review only on the latest updates. Also, what do you think about marking the before mentioned tickets as done?

I still believe that in this case it should not apply, but the changes would already be in place, regarding the other tickets if they should be passed on to done if they are ok.

2024-09-29 11:12 UTC, zrock-dev commented
I've written a script to test the endpoints. Turns out the PUT endpoint of expenses is not validating the input.

```
Expenses endpoint testing

GET
Request expense by ID 	[PROCESSED]
{
  "id": "5c98725e-1c7a-41c8-bf2c-c16663922982",
  "userId": "00000000-0000-0000-0000-000000000000",
  "amount": 100.50,
  "date": "2024-09-29T08:30:00Z",
  "description": "Purchased products",
  "category": {
    "id": "42323408-9636-4b71-aa50-81f7d5dacf0e",
    "name": "Electronics"
  }
}
Request all expenses 	[PROCESSED]
[
  {
    "id": "5c98725e-1c7a-41c8-bf2c-c16663922982",
    "userId": "00000000-0000-0000-0000-000000000000",
    "amount": 100.50,
    "date": "2024-09-29T08:30:00Z",
    "description": "Purchased products",
    "category": {
      "id": "42323408-9636-4b71-aa50-81f7d5dacf0e",
      "name": "Electronics"
    }
  }
]

POST
POST incorrect data 	[BAD REQUEST]
LOG:
status: 400
"One or more validation errors occurred."
{
  "request": [
    "The request field is required."
  ],
  "$.amount": [
    "''' is an invalid start of a value. Path: $.amount | LineNumber: 1 | BytePositionInLine: 12."
  ]
}

POST correct data 	[UNEXPECTED]
LOG:
status: 500
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_ExpenseCategory"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)


PUT
Update entry with correct data 	[PROCESSED]
Update entry with bad data 	[PROCESSED]
{
  "id": "5c98725e-1c7a-41c8-bf2c-c16663922982",
  "userId": "00000000-0000-0000-0000-000000000000",
  "amount": -100,
  "date": "2024-09-29T05:45:05.457Z",
  "description": "",
  "category": {
    "id": "42323408-9636-4b71-aa50-81f7d5dacf0e",
    "name": "Electronics"
  }
}

DELETE
Erase entry 	[PROCESSED]
[]

``` 

---
This is the script for reference.
```
#! /usr/local/bin/elvish

var base_url = 'http://localhost:5001/api/v1/incomes'

fn is_bad_request { |http_code|
    and (> $http_code 399) (< $http_code 500)
}

fn status_evaluation { |title http_code fn|
  if (eq $http_code 200) {
    printf "%s \t[PROCESSED]\n" $title
  } elif (is_bad_request $http_code) {
    printf "%s \t[BAD REQUEST]\nLOG:\nstatus: %d\n" $title $http_code
    $fn | jq '.title, .errors'
    echo
  } else {
    printf "%s \t[UNEXPECTED]\nLOG:\nstatus: %d\n" $title $http_code
    $fn | head
    echo
  }
}

fn content_request { |&print=$false &url=$base_url method body|
  if $print {
    curl -s ^
    -X $method $url ^
    -H 'accept: */*' ^
    -H 'Content-Type: application/json' ^
    -d $body ^
  } else {
    curl -s -w "%{http_code}\n"^
    -X  $method $url ^
    -H 'accept: */*' ^
    -H 'Content-Type: application/json' ^
    -d $body ^
    -o /dev/null
  }
}

fn simple_request { |&print=$false &url=$base_url method|
  if $print {
    curl -s ^
    -X $method $url ^
    -H 'accept: */*'
  } else {
    curl -s -w "%{http_code}\n"^
    -X $method $url ^
    -H 'accept: */*' ^
    -o /dev/null
  }
}

echo "Expenses endpoint testing"

var id = '5c98725e-1c7a-41c8-bf2c-c16663922982'
var request_url = (printf "%s/%s" $base_url $id)

# -- GET
var method = 'GET'
echo "\n"$method
var http_code = (simple_request &url=$request_url $method)
status_evaluation 'Request expense by ID' $http_code { simple_request &print=$true &url=$request_url $method }
if (eq $http_code 200) {
  simple_request &print=$true &url=$request_url $method | jq
}

var http_code = (simple_request $method)
status_evaluation 'Request all expenses' $http_code { simple_request &print=$true $method}
if (eq $http_code 200) {
  simple_request &print=$true $method | jq
}

# -- POST
var method = 'POST'
echo "\n"$method
var body = ^
  '{
  "amount": -1000,
  "date": "",
  "source": 9090,
  }}'
status_evaluation 'POST incorrect data' (content_request $method $body) { content_request $method $body &print=$true}

var body = ^
  '{
  "amount": -1000,
  "date": "",
  "source": 9090,
  }}'
status_evaluation 'POST correct data' (content_request $method $body) { content_request $method $body &print=$true}

# -- PUT
var method = 'PUT'
echo "\n"$method
var body = ^
  '{
  "amount": 1000,
  "date": "2024-09-29T05:48:59.254Z",
  "source": "Working on the mines",
  }}'
status_evaluation 'Update entry with correct data' (content_request &url=$request_url $method $body) { content_request &print=$true &url=$request_url $method $body }

var body = ^
  '{
  "amount": -1000,
  "date": "",
  "source": "",
  }}'
var http_code = (content_request &url=$request_url $method $body)
status_evaluation 'Update entry with bad data' $http_code { content_request &print=$true &url=$request_url $method $body }
if (eq $http_code 200) {
  simple_request &print=$true &url=$request_url 'GET' | jq
}

# -- DELETE
var method = 'DELETE'
echo "\n"$method

var http_code = (simple_request &url=$request_url $method)
status_evaluation 'Erase entry' $http_code { simple_request &print=$true &url=$request_url $method }
if (eq $http_code 200) {
  simple_request &print=$true 'GET' | jq
}

```

2024-09-29 15:39 UTC, zrock-dev commented
I have tested the incomes endpoint and found that PUT petitions are not being validated, some issues with POST requests.

```
GET
========================================
Request expense by ID 	[PROCESSED]
--------------------------------------
{
  "id": "f86a1a5b-7b58-4b7e-8244-75d2c4d2e72e",
  "userId": "00000000-0000-0000-0000-000000000000",
  "amount": 1500.00,
  "date": "2024-09-29T08:00:00Z",
  "source": "Salary"
}
========================================
Request all expenses 	[PROCESSED]
--------------------------------------
[
  {
    "id": "f86a1a5b-7b58-4b7e-8244-75d2c4d2e72e",
    "userId": "00000000-0000-0000-0000-000000000000",
    "amount": 1500.00,
    "date": "2024-09-29T08:00:00Z",
    "source": "Salary"
  }
]

POST
========================================
POST incorrect data 	[UNEXPECTED]
LOG:
status: 500
FluentValidation.ValidationException: Validation failed: 
 -- Source: A source is required Severity: Error
   at RestApi.Services.Concretes.IncomeService.CreateAsync(Income income) in /src/RestApi/Services/Concretes/IncomeService.cs:line 25
   at RestApi.Controllers.IncomeController.Create(CreateIncomeRequest request) in /src/RestApi/Controllers/IncomesController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

Request body:
{
  "amount": -1000,
  "date": "2030-09-29T05:48:59.254Z",
  "source": ""
}
--------------------------------------
========================================
POST correct data 	[UNEXPECTED]
LOG:
status: 500
FluentValidation.ValidationException: Validation failed: 
 -- Amount: the amount has to be higher to 0 Severity: Error
   at RestApi.Services.Concretes.IncomeService.CreateAsync(Income income) in /src/RestApi/Services/Concretes/IncomeService.cs:line 25
   at RestApi.Controllers.IncomeController.Create(CreateIncomeRequest request) in /src/RestApi/Controllers/IncomesController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

Request body:
{
  "amount": 1000,
  "date": "2024-09-29T05:48:59.254Z",
  "source": "Youtube revenues"
}
--------------------------------------

PUT
========================================
Update entry with correct data 	[PROCESSED]

Request body:
{
  "amount": 1000,
  "date": "2024-09-29T05:48:59.254Z",
  "source": "Working on the mines"
}
--------------------------------------
========================================
Update entry with bad data 	[PROCESSED]

Request body:
{
  "amount": -1000,
  "date": "2030-09-29T05:48:59.254Z",
  "source": ""
}
--------------------------------------

DELETE
========================================
Erase entry 	[PROCESSED]
--------------------------------------
[]
```
----

Here's the script for reference:
```
#! /usr/local/bin/elvish

var base_url = 'http://localhost:5001/api/v1/incomes'

fn is_bad_request { |http_code|
    and (> $http_code 399) (< $http_code 500)
}

fn status_evaluation { | &print=$false &body='' title http_code fn|
  echo "========================================"
  if (eq $http_code 200) {
    printf "%s \t[PROCESSED]\n" $title
  } elif (is_bad_request $http_code) {
    printf "%s \t[BAD REQUEST]\nLOG:\nstatus: %d\n" $title $http_code
    $fn | jq '.title, .errors'
  } else {
    printf "%s \t[UNEXPECTED]\nLOG:\nstatus: %d\n" $title $http_code
    $fn | head -n 5
  }

  if $print {
    echo "\nRequest body:"
    echo $body | jq
  }
  echo "--------------------------------------"
}

fn content_request { |&print=$false &url=$base_url method body|
  if $print {
    curl -s ^
    -X $method $url ^
    -H 'accept: */*' ^
    -H 'Content-Type: application/json' ^
    -d $body

  } else {
    curl -s -w "%{http_code}\n"^
    -X  $method $url ^
    -H 'accept: */*' ^
    -H 'Content-Type: application/json' ^
    -d $body ^
    -o /dev/null
  }
}

fn simple_request { |&print=$false &url=$base_url method|
  if $print {
    curl -s ^
    -X $method $url ^
    -H 'accept: */*'
  } else {
    curl -s -w "%{http_code}\n"^
    -X $method $url ^
    -H 'accept: */*' ^
    -o /dev/null
  }
}

var id = 'f86a1a5b-7b58-4b7e-8244-75d2c4d2e72e'
var request_url = (printf "%s/%s" $base_url $id)

# -- GET
var method = 'GET'
echo "\n"$method
var http_code = (simple_request &url=$request_url $method)
status_evaluation 'Request expense by ID' $http_code { simple_request &print=$true &url=$request_url $method }
if (eq $http_code 200) {
  simple_request &print=$true &url=$request_url $method | jq
}

var http_code = (simple_request $method)
status_evaluation 'Request all expenses' $http_code { simple_request &print=$true $method}
if (eq $http_code 200) {
  simple_request &print=$true $method | jq
}

# -- POST
var method = 'POST'
echo "\n"$method
var body = ^
  '{
  "amount": -1000,
  "date": "2030-09-29T05:48:59.254Z",
  "source": ""
  }'
status_evaluation &print=$true &body=$body 'POST incorrect data' (content_request $method $body) { content_request $method $body &print=$true}

var body = ^
  '{
  "amount": 1000,
  "date": "2024-09-29T05:48:59.254Z",
  "source": "Youtube revenues"
  }'
status_evaluation &print=$true &body=$body 'POST correct data' (content_request $method $body) { content_request $method $body &print=$true}

# -- PUT
var method = 'PUT'
echo "\n"$method
var body = ^
  '{
  "amount": 1000,
  "date": "2024-09-29T05:48:59.254Z",
  "source": "Working on the mines"
  }'
status_evaluation &print=$true &body=$body 'Update entry with correct data' (content_request &url=$request_url $method $body) { content_request &print=$true &url=$request_url $method $body }

var body = ^
  '{
  "amount": -1000,
  "date": "2030-09-29T05:48:59.254Z",
  "source": ""
  }'
var http_code = (content_request &url=$request_url $method $body)
status_evaluation &print=$true &body=$body 'Update entry with bad data' $http_code { content_request &print=$true &url=$request_url $method $body }

# -- DELETE
var method = 'DELETE'
echo "\n"$method

var http_code = (simple_request &url=$request_url $method)
status_evaluation 'Erase entry' $http_code { simple_request &print=$true &url=$request_url $method }
if (eq $http_code 200) {
  simple_request &print=$true 'GET' | jq
}
```

2024-09-29 17:19 UTC, zrock-dev commented
I have tested the User endpoints, I couldn't update a user's profile even tho I had logged in.

```

GET
========================================
Attempt: Request entry, ID:b6232e7d-7414-4220-a312-08aaec5b8333
Result: 	[PROCESSED]

--------------------------------------
{
  "id": "b6232e7d-7414-4220-a312-08aaec5b8333",
  "name": "Jorge Curioso",
  "email": "fake.email@gmail.com",
  "password": "aAr)R6@%b,V$:Zu]9}v/p+"
}
========================================
Attempt: Request all expenses
Result: 	[PROCESSED]

--------------------------------------
[
  {
    "id": "0c73dcef-e478-4a6e-bc69-b3c627d5f1d9",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "7b6701b4-d22e-4dc3-be73-b9f44aa465c4",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123"
  },
  {
    "id": "e3291321-fe94-4f47-b30e-3c00434e4905",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "7521b553-a89b-4a91-a65f-8f9443b89db2",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "1d4651e0-8857-47c5-8b08-8cc05fbe1f97",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "b6232e7d-7414-4220-a312-08aaec5b8333",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "728fe975-d7a1-4d5b-9d73-321fcaada6d6",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "9beeb160-4c46-4dcd-9b81-80f9ff35b98c",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "dc32edc3-f217-4190-a864-fb1217f0eeb6",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "da6fdbda-dbb3-4a63-8257-0078b4562ec7",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "4b7ad459-f987-487d-8d4e-7db319b8376d",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "99e6c5d0-ea12-44c5-b4e5-c55a2a9c6d49",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "5f004146-6607-45b5-afde-868fc4fcbe2c",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "5bacf5c8-0965-4ddc-bcb3-690445751700",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "a42ddba4-9ea3-4382-a316-a60cce004cf2",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  },
  {
    "id": "4b425127-0f3c-468b-987e-cde636397a7c",
    "name": "Jorge Curioso",
    "email": "fake.email@gmail.com",
    "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  }
]

POST
========================================
Attempt: Incorrect data
Result: 	[BAD REQUEST]
Status: 400
LOG:
"One or more validation errors occurred."
{
  "request": [
    "The request field is required."
  ],
  "$.name": [
    "The JSON value could not be converted to System.String. Path: $.name | LineNumber: 1 | BytePositionInLine: 14."
  ]
}

Request body:
{
  "name": 1000,
  "email": "not-valid-email",
  "password": ""
}
--------------------------------------
========================================
Attempt: Correct data
Result: 	[PROCESSED]


Request body:
{
  "name": "Jorge Curioso",
  "email": "fake.email@gmail.com",
  "password": "aAr)R6@%b,V$:Zu]9}v/p+"
}
--------------------------------------
========================================
Attempt: Log in
Result: 	[PROCESSED]


Request body:
"b6232e7d-7414-4220-a312-08aaec5b8333"
--------------------------------------

PUT
========================================
Attempt: Update entry with correct data
Result: 	[BAD REQUEST]
Status: 405
LOG:

Request body:
{
  "name": "Pedro navaja",
  "email": "pedro-navaja@gmail.com",
  "password": "D<FM^6w5W%knXe(;H4Ty+N"
}
--------------------------------------
========================================
Attempt: Update entry with bad data
Result: 	[BAD REQUEST]
Status: 405
LOG:

Request body:
{
  "name": 1000,
  "email": "not-valid-email",
  "password": ""
}
--------------------------------------

DELETE
========================================
Attempt: Erase entry, ID:b6232e7d-7414-4220-a312-08aaec5b8333
Result: 	[PROCESSED]

--------------------------------------
========================================
Attempt: Log in with deleted user
Result: 	[BAD REQUEST]
Status: 405
LOG:

Request body:
"b6232e7d-7414-4220-a312-08aaec5b8333"
--------------------------------------
``` 

Here's the script.
```
#! /usr/local/bin/elvish

var hostname = 'http://localhost:5001/api/v1/users'
var id = 'b6232e7d-7414-4220-a312-08aaec5b8333'
var method = ''
var http_code = 0
var path = ''

var good_request = ^
  '{
  "name": "Jorge Curioso",
  "email": "fake.email@gmail.com",
  "password": "aAr)R6@%b,V$:Zu]9}v/p+"
  }'
var bad_request = ^
  '{
  "name": 1000,
  "email": "not-valid-email",
  "password": ""
  }'
var body = ''

fn is_bad_request { |http_code|
    and (> $http_code 399) (< $http_code 500)
}

fn status_evaluation { | &print=$false &body='' title http_code fn|
  echo "========================================"
  printf "Attempt: %s\n" $title
  if (eq $http_code 200) {
    echo "Result: \t[PROCESSED]\n"
  } elif (is_bad_request $http_code) {
    printf "Result: \t[BAD REQUEST]\nStatus: %d\nLOG:\n" $http_code
    $fn | jq '.title, .errors'
  } else {
    printf "Result: \t[UNEXPECTED]\nStatus: %d\nLOG:\n" $http_code
    $fn | head -n 5
  }

  if $print {
    echo "\nRequest body:"
    echo $body | jq
  }
  echo "--------------------------------------"
}

fn content_request { |&print=$false &path='' method body|
  var url = (printf "%s/%s" $hostname $path)

  if $print {
    curl -s ^
    -X $method $url ^
    -H 'accept: */*' ^
    -H 'Content-Type: application/json' ^
    -d $body

  } else {
    curl -s -w "%{http_code}\n"^
    -X  $method $url ^
    -H 'accept: */*' ^
    -H 'Content-Type: application/json' ^
    -d $body ^
    -o /dev/null
  }
}

fn simple_request { |&print=$false &path='' method|
  var url = (printf "%s/%s" $hostname $path)

  if $print {
    curl -s ^
    -X $method $url ^
    -H 'accept: */*'
  } else {
    curl -s -w "%{http_code}\n"^
    -X $method $url ^
    -H 'accept: */*' ^
    -o /dev/null
  }
}

# -- GET
set method = 'GET'
echo "\n"$method

set http_code = (simple_request &path=$id $method)
status_evaluation (printf "Request entry, ID:%s" $id ) $http_code { simple_request &print=$true &path=$id $method }
if (eq $http_code 200) {
  simple_request &print=$true &path=$id $method | jq
}

set http_code = (simple_request $method)
status_evaluation 'Request all expenses' $http_code { simple_request &print=$true $method}
if (eq $http_code 200) {
  simple_request &print=$true $method | jq
}

# -- POST
set method = 'POST'
echo "\n"$method
set path = 'register'

set body = $bad_request
status_evaluation &print=$true &body=$body 'Incorrect data' (content_request &path=$path $method $body) { content_request &path=$path &print=$true $method $body }

set body = $good_request
status_evaluation &print=$true &body=$body 'Correct data' (content_request &path=$path $method $body) { content_request &path=$path &print=$true $method $body }

set path = 'Login/'
set body = (printf '"%s"' $id)
status_evaluation &print=$true &body=$body 'Log in' (content_request &pa [...]

2024-09-29 20:25 UTC, JosuePrado commented
> I have tested the User endpoints, I couldn't update a user's profile even tho I was logged in.
> 
> ```
> 
> GET
> ========================================
> Attempt: Request entry, ID:b6232e7d-7414-4220-a312-08aaec5b8333
> Result: 	[PROCESSED]
> 
> --------------------------------------
> {
>   "id": "b6232e7d-7414-4220-a312-08aaec5b8333",
>   "name": "Jorge Curioso",
>   "email": "fake.email@gmail.com",
>   "password": "aAr)R6@%b,V$:Zu]9}v/p+"
> }
> ========================================
> Attempt: Request all expenses
> Result: 	[PROCESSED]
> 
> --------------------------------------
> [
>   {
>     "id": "0c73dcef-e478-4a6e-bc69-b3c627d5f1d9",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "7b6701b4-d22e-4dc3-be73-b9f44aa465c4",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
>     "name": "John Doe",
>     "email": "john.doe@example.com",
>     "password": "password123"
>   },
>   {
>     "id": "e3291321-fe94-4f47-b30e-3c00434e4905",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "7521b553-a89b-4a91-a65f-8f9443b89db2",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "1d4651e0-8857-47c5-8b08-8cc05fbe1f97",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "b6232e7d-7414-4220-a312-08aaec5b8333",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "728fe975-d7a1-4d5b-9d73-321fcaada6d6",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "9beeb160-4c46-4dcd-9b81-80f9ff35b98c",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "dc32edc3-f217-4190-a864-fb1217f0eeb6",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "da6fdbda-dbb3-4a63-8257-0078b4562ec7",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "4b7ad459-f987-487d-8d4e-7db319b8376d",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "99e6c5d0-ea12-44c5-b4e5-c55a2a9c6d49",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "5f004146-6607-45b5-afde-868fc4fcbe2c",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "5bacf5c8-0965-4ddc-bcb3-690445751700",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "a42ddba4-9ea3-4382-a316-a60cce004cf2",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   },
>   {
>     "id": "4b425127-0f3c-468b-987e-cde636397a7c",
>     "name": "Jorge Curioso",
>     "email": "fake.email@gmail.com",
>     "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   }
> ]
> 
> POST
> ========================================
> Attempt: Incorrect data
> Result: 	[BAD REQUEST]
> Status: 400
> LOG:
> "One or more validation errors occurred."
> {
>   "request": [
>     "The request field is required."
>   ],
>   "$.name": [
>     "The JSON value could not be converted to System.String. Path: $.name | LineNumber: 1 | BytePositionInLine: 14."
>   ]
> }
> 
> Request body:
> {
>   "name": 1000,
>   "email": "not-valid-email",
>   "password": ""
> }
> --------------------------------------
> ========================================
> Attempt: Correct data
> Result: 	[PROCESSED]
> 
> 
> Request body:
> {
>   "name": "Jorge Curioso",
>   "email": "fake.email@gmail.com",
>   "password": "aAr)R6@%b,V$:Zu]9}v/p+"
> }
> --------------------------------------
> ========================================
> Attempt: Log in
> Result: 	[PROCESSED]
> 
> 
> Request body:
> "b6232e7d-7414-4220-a312-08aaec5b8333"
> --------------------------------------
> 
> PUT
> ========================================
> Attempt: Update entry with correct data
> Result: 	[BAD REQUEST]
> Status: 405
> LOG:
> 
> Request body:
> {
>   "name": "Pedro navaja",
>   "email": "pedro-navaja@gmail.com",
>   "password": "D<FM^6w5W%knXe(;H4Ty+N"
> }
> --------------------------------------
> ========================================
> Attempt: Update entry with bad data
> Result: 	[BAD REQUEST]
> Status: 405
> LOG:
> 
> Request body:
> {
>   "name": 1000,
>   "email": "not-valid-email",
>   "password": ""
> }
> --------------------------------------
> 
> DELETE
> ========================================
> Attempt: Erase entry, ID:b6232e7d-7414-4220-a312-08aaec5b8333
> Result: 	[PROCESSED]
> 
> --------------------------------------
> ========================================
> Attempt: Log in with deleted user
> Result: 	[BAD REQUEST]
> Status: 405
> LOG:
> 
> Request body:
> "b6232e7d-7414-4220-a312-08aaec5b8333"
> --------------------------------------
> ```
> 
> Here's the script.
> 
> ```
> #! /usr/local/bin/elvish
> 
> var hostname = 'http://localhost:5001/api/v1/users'
> var id = 'b6232e7d-7414-4220-a312-08aaec5b8333'
> var method = ''
> var http_code = 0
> var path = ''
> 
> var good_request = ^
>   '{
>   "name": "Jorge Curioso",
>   "email": "fake.email@gmail.com",
>   "password": "aAr)R6@%b,V$:Zu]9}v/p+"
>   }'
> var bad_request = ^
>   '{
>   "name": 1000,
>   "email": "not-valid-email",
>   "password": ""
>   }'
> var body = ''
> 
> fn is_bad_request { |http_code|
>     and (> $http_code 399) (< $http_code 500)
> }
> 
> fn status_evaluation { | &print=$false &body='' title http_code fn|
>   echo "========================================"
>   printf "Attempt: %s\n" $title
>   if (eq $http_code 200) {
>     echo "Result: \t[PROCESSED]\n"
>   } elif (is_bad_request $http_code) {
>     printf "Result: \t[BAD REQUEST]\nStatus: %d\nLOG:\n" $http_code
>     $fn | jq '.title, .errors'
>   } else {
>     printf "Result: \t[UNEXPECTED]\nStatus: %d\nLOG:\n" $http_code
>     $fn | head -n 5
>   }
> 
>   if $print {
>     echo "\nRequest body:"
>     echo $body | jq
>   }
>   echo "--------------------------------------"
> }
> 
> fn content_request { |&print=$false &path='' method body|
>   var url = (printf "%s/%s" $hostname $path)
> 
>   if $print {
>     curl -s ^
>     -X $method $url ^
>     -H 'accept: */*' ^
>     -H 'Content-Type: application/json' ^
>     -d $body
> 
>   } else {
>     curl -s -w "%{http_code}\n"^
>     -X  $method $url ^
>     -H 'accept: */*' ^
>     -H 'Content-Type: application/json' ^
>     -d $body ^
>     -o /dev/null
>   }
> }
> 
> fn simple_request { |&print=$false &path='' method|
>   var url = (printf "%s/%s" $hostname $path)
> 
>   if $print {
>     curl -s ^
>     -X $method $url ^
>     -H 'accept: */*'
>   } else {
>     curl -s -w "%{http_code}\n"^
>     -X $method $url ^
>     -H 'accept: */*' ^
>     -o /dev/null
>   }
> }
> 
> # -- GET
> set method = 'GET'
> echo "\n"$method
> 
> set http_code = (simple_request &path=$id $method)
> status_evaluation (printf "Request entry, ID:%s" $id ) $http_code { simple_request &print=$true &path=$id $method }
> if (eq $http_code 200) {
>   simple_request &print=$true &path=$id $method | jq
> }
> 
> set http_code = (simple_request $method)
> status_evaluation 'Request all expenses' $http_code { simple_request &print=$true $method}
> if (eq $http_co [...]

2024-09-29 22:20 UTC, zrock-dev approved these changes
Good job.

2024-09-29 22:22 UTC, zrock-dev commented
[expenses-outcome.txt](https://github.com/user-attachments/files/17181559/expenses-outcome.txt)
[incomes-outcome.txt](https://github.com/user-attachments/files/17181560/incomes-outcome.txt)
[users-outcome.txt](https://github.com/user-attachments/files/17181561/users-outcome.txt)

2024-09-29 22:23 UTC, merged

2024-09-29 22:50 UTC, zrock-dev commented
Following this merge, the user now can edit a specific entry through the PUT endpoint of both expense and income logs and delete them. Retrieving data is also available and a client can retrieve all the logs or a specific one. Given that these feature have been implemented, I'll move [[ID-13] Log edition](https://trello.com/b/85HXBmp0/expensetracker6) and [[ID-9] Log Access](https://trello.com/c/8NS6aZk1/7-id-9-log-access) to DONE.